

export const POEM_TYPES: string[] = [
  'Lục Bát',
  'Song Thất Lục Bát',
  'Thơ Tự Do',
  'Haiku',
  'Sonnet',
  'Thơ 5 chữ',
  'Thơ 7 chữ',
  'Thơ 8 chữ',
];

export const POEM_STYLES: string[] = [
  'Lãng mạn',
  'Bi tráng',
  'Hiện đại',
  'Cổ điển',
  'Siêu thực',
  'Hài hước',
  'Trữ tình',
  'Anh hùng ca',
];

export const POEM_CONTEXTS: string[] = [
  'Tình yêu đôi lứa',
  'Thiên nhiên hùng vĩ',
  'Cuộc sống thường nhật',
  'Xã hội và con người',
  'Triết lý nhân sinh',
  'Gia đình',
  'Bạn bè',
];

export const EMOTIONS: string[] = [
  'Vui tươi',
  'Buồn bã',
  'Hy vọng',
  'Giận dữ',
  'Bình yên',
  'Hoài niệm',
  'Hứng khởi',
  'Cô đơn',
  'Lãng mạn',
  'Trầm tư',
  'Đam mê',
  'Bí ẩn',
  'Lo lắng',
  'Thất vọng',
  'Tự hào',
  'Ngạc nhiên',
  'Can đảm',
  'Tiếc nuối',
  'Thanh thản',
  'Ghen tị',
  'Bối rối',
  'Tò mò',
];

export const AUDIENCE_AGES: string[] = [
  'Thiếu nhi',
  'Thanh thiếu niên',
  'Người lớn',
  'Mọi lứa tuổi',
];

export const SUGGESTED_TOPICS: string[] = [
  'Hoàng hôn trên biển',
  'Cơn mưa rào mùa hạ',
  'Nỗi cô đơn giữa thành phố đông đúc',
  'Vẻ đẹp của một bông hoa dại',
  'Ký ức tuổi thơ bên mái nhà xưa',
  'Dòng sông quê hương',
  'Đêm trăng tĩnh lặng',
  'Giấc mơ dang dở',
  'Tình bạn diệu kỳ',
  'Sài Gòn về đêm',
  'Hà Nội mùa thu',
  'Một tách cà phê buổi sáng',
  'Nỗi buồn của lá rụng',
  'Hy vọng từ mầm cây mới nhú',
  'Tiếng đàn dương cầm trong đêm',
  'Cái ôm của mẹ',
  'Bước chân trên con đường vắng',
  'Ngọn hải đăng cô độc',
  'Tình yêu đầu đời trong sáng',
  'Nỗi đau của sự chia ly',
  'Sức mạnh của sự tha thứ',
  'Tiếng sóng vỗ bờ',
  'Cánh đồng lúa chín vàng',
  'Bầu trời đầy sao',
  'Chuyến tàu cuối cùng trong ngày',
  'Cuốn sách cũ trên giá',
  'Lời hứa chưa thành',
  'Vẻ đẹp của lao động',
  'Sự im lặng của núi rừng',
  'Giọt sương mai trên lá',
  'Nụ cười của trẻ thơ',
  'Ánh mắt người thương',
  'Con diều giấy bay cao',
  'Mùi của đất sau cơn mưa',
  'Nỗi nhớ nhà của người con xa xứ',
  'Sự khắc nghiệt của thời gian',
  'Vòng xoáy của số phận',
  'Đi tìm bản ngã',
  'Ánh lửa bập bùng trong đêm đông',
  'Một chiều cuối năm',
  'Chợ Tết ngày xưa',
  'Giọt nước mắt hạnh phúc',
  'Bức thư tay chưa gửi',
  'Con đường mòn quen thuộc',
  'Tiếng chuông chùa buổi sớm',
  'Sự hối tiếc muộn màng',
  'Lòng dũng cảm đối mặt với thử thách',
  'Vẻ đẹp của sự không hoàn hảo',
  'Gánh hàng rong của mẹ',
  'Thành phố đã ngủ say',
  'Khúc nhạc buồn ai đang nghe',
  'Gặp gỡ và định mệnh',
  'Khoảng trống trong tâm hồn',
  'Bình yên trong tâm bão',
  'Lời tỏ tình vụng về',
  'Giấc ngủ của người cha già',
  'Chuyến xe bus đến miền xa lạ',
  'Cánh chim bay về phương Nam',
  'Nỗi ám ảnh của quá khứ',
  'Vẻ đẹp tri thức',
  'Lời ru của bà',
  'Ngôi trường cũ và những kỷ niệm',
  'Sự mong manh của cuộc sống',
  'Triết lý về một hạt cát',
  'Khát vọng tự do',
  'Vẻ đẹp của sự hy sinh thầm lặng',
  'Trận bóng đá ngoài sân đình',
  'Mùa hoa phượng nở',
  'Đà Lạt sương mù',
  'Vịnh Hạ Long hùng vĩ',
  'Phố cổ Hội An trầm mặc',
  'Dòng người hối hả',
  'Cái bắt tay của sự hòa giải',
  'Tương lai trong trí tưởng tượng',
  'Vẻ đẹp của một ngày mưa',
  'Bản giao hưởng của thiên nhiên',
  'Sự tái sinh của phượng hoàng',
  'Lời cảm ơn chưa nói',
  'Cuộc đối thoại với chính mình',
  'Màu xanh của hy vọng',
  'Nỗi sợ hãi vô hình',
  'Sức sống mãnh liệt của cây xương rồng',
  'Vị của biển',
  'Âm thanh của sự tĩnh lặng',
  'Mối tình đơn phương',
  'Sự kỳ diệu của vũ trụ',
  'Một ngày sống chậm lại',
  'Lời nguyện cầu dưới ánh nến',
  'Cuộc đời là một chuyến đi',
  'Sự trưởng thành sau vấp ngã',
  'Giọt cà phê đắng',
  'Nỗi nhớ một người không còn nữa',
  'Tiếng rao hàng trong con hẻm nhỏ',
  'Cánh cửa thời gian',
  'Vẻ đẹp của sự thật',
  'Bài học từ một loài cây',
  'Sự giao mùa của đất trời',
  'Ngọn gió lang thang',
  'Hạnh phúc giản đơn',
  'Lời tạm biệt hoàng hôn',
];

export const FONT_OPTIONS: { name: string; family: string }[] = [
  { name: 'Mặc định (Quicksand)', family: "'Quicksand', sans-serif" },
  { name: 'Cổ điển (Playfair Display)', family: "'Playfair Display', serif" },
  { name: 'Hiện đại (Montserrat)', family: "'Montserrat', sans-serif" },
  { name: 'Viết tay (Dancing Script)', family: "'Dancing Script', cursive" },
  { name: 'In đậm (Roboto Slab)', family: "'Roboto Slab', serif" },
  // Serif Fonts
  { name: 'Trang trọng (Merriweather)', family: "'Merriweather', serif" },
  { name: 'Nhẹ nhàng (Lora)', family: "'Lora', serif" },
  { name: 'Cổ kính (EB Garamond)', family: "'EB Garamond', serif" },
  { name: 'Tinh tế (Cormorant Garamond)', family: "'Cormorant Garamond', serif" },
  { name: 'Rõ ràng (Noto Serif)', family: "'Noto Serif', serif" },
  // Sans-serif Fonts
  { name: 'Phổ biến (Roboto)', family: "'Roboto', sans-serif" },
  { name: 'Thân thiện (Open Sans)', family: "'Open Sans', sans-serif" },
  { name: 'Năng động (Lato)', family: "'Lato', sans-serif" },
  { name: 'Tối giản (Inter)', family: "'Inter', sans-serif" },
  { name: 'Tròn trịa (Poppins)', family: "'Poppins', sans-serif" },
  { name: 'Mạnh mẽ (Oswald)', family: "'Oswald', sans-serif" },
  { name: 'Thanh lịch (Raleway)', family: "'Raleway', sans-serif" },
  { name: 'Tiêu đề (Josefin Sans)', family: "'Josefin Sans', sans-serif" },
  { name: 'Dễ đọc (Arimo)', family: "'Arimo', sans-serif" },
  { name: 'Hữu ích (Source Sans 3)', family: "'Source Sans 3', sans-serif" },
  // Monospace Fonts
  { name: 'Máy chữ (Roboto Mono)', family: "'Roboto Mono', monospace" },
  { name: 'Lập trình (Source Code Pro)', family: "'Source Code Pro', monospace" },
  // Handwriting/Cursive Fonts
  { name: 'Mềm mại (Pacifico)', family: "'Pacifico', cursive" },
  { name: 'Ngẫu hứng (Caveat)', family: "'Caveat', cursive" },
  { name: 'Đơn giản (Patrick Hand)', family: "'Patrick Hand', cursive" },
];